//! Bulk operations for Message entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateMessageDto;
use crate::application::service::MessageService;
use crate::domain::entity::Message;

/// Bulk operation handler for Message entities.
///
/// Wraps `MessageService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type MessageBulkService = GenericBulkService<Message, CreateMessageDto, MessageService>;

// <<< CUSTOM
// END CUSTOM
