//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod message_bulk;
pub mod thread_bulk;

pub use message_bulk::MessageBulkService;
pub use thread_bulk::ThreadBulkService;

// <<< CUSTOM
// END CUSTOM
