//! Bulk operations for Thread entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateThreadDto;
use crate::application::service::ThreadService;
use crate::domain::entity::Thread;

/// Bulk operation handler for Thread entities.
///
/// Wraps `ThreadService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ThreadBulkService = GenericBulkService<Thread, CreateThreadDto, ThreadService>;

// <<< CUSTOM
// END CUSTOM
