//! Message DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Message;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::Channel;
use crate::domain::entity::Direction;
use crate::domain::entity::MessageStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Message
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "thread_id")]
    pub thread_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub direction: Direction,
    pub channel: Channel,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "external_id")]
    pub external_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "address_from")]
    pub address_from: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "address_to")]
    pub address_to: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub status: MessageStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Message
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "thread_id")]
    pub thread_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub direction: Direction,
    pub channel: Channel,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "external_id")]
    pub external_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "address_from")]
    pub address_from: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "address_to")]
    pub address_to: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub status: MessageStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Message
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchMessageDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "thread_id")]
    pub thread_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<Direction>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<Channel>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "external_id")]
    pub external_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "address_from")]
    pub address_from: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "address_to")]
    pub address_to: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<MessageStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "occurred_at")]
    pub occurred_at: Option<DateTime<Utc>>,
}

impl PatchMessageDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.thread_id.is_some() || self.company_id.is_some() || self.direction.is_some() || self.channel.is_some() || self.external_id.is_some() || self.address_from.is_some() || self.address_to.is_some() || self.body.is_some() || self.status.is_some() || self.failure_reason.is_some() || self.occurred_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Message entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MessageResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub thread_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub direction: Direction,
    pub channel: Channel,
    pub external_id: Option<String>,
    pub address_from: Option<String>,
    pub address_to: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub status: MessageStatus,
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Message entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MessageListResponseDto {
    /// List of items
    pub items: Vec<MessageResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl MessageListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<MessageResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct MessageSummaryDto {
    pub id: Uuid,
    pub thread_id: Uuid,
    pub company_id: Uuid,
    pub direction: Direction,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Message> for MessageResponseDto {
    fn from(entity: Message) -> Self {
        Self {
            id: entity.id,
            thread_id: entity.thread_id,
            company_id: entity.company_id,
            direction: entity.direction,
            channel: entity.channel,
            external_id: entity.external_id,
            address_from: entity.address_from,
            address_to: entity.address_to,
            body: entity.body,
            status: entity.status,
            failure_reason: entity.failure_reason,
            occurred_at: entity.occurred_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Message> for MessageSummaryDto {
    fn from(entity: Message) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            thread_id: entity.thread_id,
            company_id: entity.company_id,
            direction: entity.direction,
            created_at,
        }
    }
}

impl From<CreateMessageDto> for Message {
    fn from(dto: CreateMessageDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            thread_id: dto.thread_id,
            company_id: dto.company_id,
            direction: dto.direction,
            channel: dto.channel,
            external_id: dto.external_id,
            address_from: dto.address_from,
            address_to: dto.address_to,
            body: dto.body,
            status: dto.status,
            failure_reason: dto.failure_reason,
            occurred_at: dto.occurred_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Message> for MessageResponseDto {
    fn from(entity: &Message) -> Self {
        Self {
            id: entity.id.clone(),
            thread_id: entity.thread_id.clone(),
            company_id: entity.company_id.clone(),
            direction: entity.direction.clone(),
            channel: entity.channel.clone(),
            external_id: entity.external_id.clone(),
            address_from: entity.address_from.clone(),
            address_to: entity.address_to.clone(),
            body: entity.body.clone(),
            status: entity.status.clone(),
            failure_reason: entity.failure_reason.clone(),
            occurred_at: entity.occurred_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateMessageDto> for Message {
    fn from_create_dto(dto: CreateMessageDto) -> backbone_core::ServiceResult<Self> {
        Ok(Message::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateMessageDto> for Message {
    fn apply_update(mut self, dto: UpdateMessageDto) -> backbone_core::ServiceResult<Self> {
        self.thread_id = dto.thread_id;
        self.company_id = dto.company_id;
        self.direction = dto.direction;
        self.channel = dto.channel;
        self.external_id = dto.external_id;
        self.address_from = dto.address_from;
        self.address_to = dto.address_to;
        self.body = dto.body;
        self.status = dto.status;
        self.failure_reason = dto.failure_reason;
        self.occurred_at = dto.occurred_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Message here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

