//! Thread DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Thread;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::Channel;
use crate::domain::entity::ThreadStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Thread
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateThreadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub channel: Channel,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "external_ref")]
    pub external_ref: Option<String>,
    pub status: ThreadStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_message_at")]
    pub last_message_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Thread
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateThreadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    pub channel: Channel,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "external_ref")]
    pub external_ref: Option<String>,
    pub status: ThreadStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_message_at")]
    pub last_message_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Thread
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchThreadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<Channel>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "external_ref")]
    pub external_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ThreadStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_message_at")]
    pub last_message_at: Option<DateTime<Utc>>,
}

impl PatchThreadDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.channel.is_some() || self.party_id.is_some() || self.subject_type.is_some() || self.subject_id.is_some() || self.external_ref.is_some() || self.status.is_some() || self.last_message_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Thread entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ThreadResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub channel: Channel,
    pub party_id: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub external_ref: Option<String>,
    pub status: ThreadStatus,
    pub last_message_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Thread entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ThreadListResponseDto {
    /// List of items
    pub items: Vec<ThreadResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ThreadListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ThreadResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ThreadSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub channel: Channel,
    pub party_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Thread> for ThreadResponseDto {
    fn from(entity: Thread) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            channel: entity.channel,
            party_id: entity.party_id,
            subject_type: entity.subject_type,
            subject_id: entity.subject_id,
            external_ref: entity.external_ref,
            status: entity.status,
            last_message_at: entity.last_message_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Thread> for ThreadSummaryDto {
    fn from(entity: Thread) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            channel: entity.channel,
            party_id: entity.party_id,
            created_at,
        }
    }
}

impl From<CreateThreadDto> for Thread {
    fn from(dto: CreateThreadDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            channel: dto.channel,
            party_id: dto.party_id,
            subject_type: dto.subject_type,
            subject_id: dto.subject_id,
            external_ref: dto.external_ref,
            status: dto.status,
            last_message_at: dto.last_message_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Thread> for ThreadResponseDto {
    fn from(entity: &Thread) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            channel: entity.channel.clone(),
            party_id: entity.party_id.clone(),
            subject_type: entity.subject_type.clone(),
            subject_id: entity.subject_id.clone(),
            external_ref: entity.external_ref.clone(),
            status: entity.status.clone(),
            last_message_at: entity.last_message_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateThreadDto> for Thread {
    fn from_create_dto(dto: CreateThreadDto) -> backbone_core::ServiceResult<Self> {
        Ok(Thread::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateThreadDto> for Thread {
    fn apply_update(mut self, dto: UpdateThreadDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.channel = dto.channel;
        self.party_id = dto.party_id;
        self.subject_type = dto.subject_type;
        self.subject_id = dto.subject_id;
        self.external_ref = dto.external_ref;
        self.status = dto.status;
        self.last_message_at = dto.last_message_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Thread here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
