//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod message_domain_policy;
pub mod thread_domain_policy;

pub use message_domain_policy::MessageDomainPolicy;
pub use thread_domain_policy::ThreadDomainPolicy;

// <<< CUSTOM
// END CUSTOM
