//! Application service for Message entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `message_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateMessageDto, UpdateMessageDto};
use crate::domain::entity::Message;
use crate::infrastructure::persistence::MessageRepository;

/// Application service for Message entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `message_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct MessageServiceCustom {
///     inner: Arc<MessageService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type MessageService = GenericCrudService<
    Message,
    CreateMessageDto,
    UpdateMessageDto,
    MessageRepository,
>;

// <<< CUSTOM
// END CUSTOM
