-- Message Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the communication.messages table.
-- Customize this file to add your initial data.

-- INSERT INTO communication.messages (
--     id,
--     thread_id,
--     company_id,
--     direction,
--     channel,
--     external_id,
--     address_from,
--     address_to,
--     body,
--     status,
--     failure_reason,
--     occurred_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO communication.messages (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

