-- Thread Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the communication.threads table.
-- Customize this file to add your initial data.

-- INSERT INTO communication.threads (
--     id,
--     company_id,
--     channel,
--     party_id,
--     subject_type,
--     subject_id,
--     external_ref,
--     status,
--     last_message_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO communication.threads (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

