-- Company RLS fence for communication module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for communication.messages
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE communication.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE communication.messages FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS messages_company_isolation ON communication.messages;
CREATE POLICY messages_company_isolation ON communication.messages
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for communication.threads
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE communication.threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE communication.threads FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS threads_company_isolation ON communication.threads;
CREATE POLICY threads_company_isolation ON communication.threads
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

