-- Enum types for communication module
-- Generated by metaphor-schema

-- Create direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'direction') THEN
        CREATE TYPE direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

-- Create message_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'message_status') THEN
        CREATE TYPE message_status AS ENUM ('received', 'queued', 'sent', 'delivered', 'failed');
    END IF;
END
$$;

-- Create channel enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'channel') THEN
        CREATE TYPE channel AS ENUM ('whatsapp', 'email', 'sms');
    END IF;
END
$$;

-- Create thread_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'thread_status') THEN
        CREATE TYPE thread_status AS ENUM ('open', 'closed');
    END IF;
END
$$;

