-- Audit Triggers Migration for communication module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Message (communication.messages)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION communication.messages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS messages_insert_audit ON communication.messages;
CREATE TRIGGER messages_insert_audit BEFORE INSERT ON communication.messages
    FOR EACH ROW EXECUTE FUNCTION communication.messages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS messages_update_audit ON communication.messages;
CREATE TRIGGER messages_update_audit BEFORE UPDATE ON communication.messages
    FOR EACH ROW EXECUTE FUNCTION communication.messages_audit_timestamp();

-- ==============================================================================
-- Table: Thread (communication.threads)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION communication.threads_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS threads_insert_audit ON communication.threads;
CREATE TRIGGER threads_insert_audit BEFORE INSERT ON communication.threads
    FOR EACH ROW EXECUTE FUNCTION communication.threads_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS threads_update_audit ON communication.threads;
CREATE TRIGGER threads_update_audit BEFORE UPDATE ON communication.threads
    FOR EACH ROW EXECUTE FUNCTION communication.threads_audit_timestamp();

