-- Migration: Create messages table
-- Generated by metaphor-schema

-- Create direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'direction') THEN
        CREATE TYPE direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

-- Create channel enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'channel') THEN
        CREATE TYPE channel AS ENUM ('whatsapp', 'email', 'sms');
    END IF;
END
$$;

-- Create message_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'message_status') THEN
        CREATE TYPE message_status AS ENUM ('received', 'queued', 'sent', 'delivered', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS communication;

CREATE TABLE IF NOT EXISTS communication.messages (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    thread_id UUID NOT NULL,
    company_id UUID NOT NULL,
    direction direction NOT NULL,
    channel channel NOT NULL,
    external_id TEXT,
    address_from TEXT,
    address_to TEXT,
    body TEXT NOT NULL,
    status message_status NOT NULL DEFAULT 'received',
    failure_reason TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_channel_external_id ON communication.messages (channel, external_id);

CREATE INDEX IF NOT EXISTS idx_messages_thread_id ON communication.messages (thread_id);

CREATE INDEX IF NOT EXISTS idx_messages_status ON communication.messages (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_messages_metadata_gin ON communication.messages USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_messages_metadata_deleted_at ON communication.messages ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_messages_metadata_created_at ON communication.messages ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_messages_metadata_updated_at ON communication.messages ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION communication.messages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS messages_insert_audit ON communication.messages;
CREATE TRIGGER messages_insert_audit BEFORE INSERT ON communication.messages
    FOR EACH ROW EXECUTE FUNCTION communication.messages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS messages_update_audit ON communication.messages;
CREATE TRIGGER messages_update_audit BEFORE UPDATE ON communication.messages
    FOR EACH ROW EXECUTE FUNCTION communication.messages_audit_timestamp();
