-- Migration: Create threads table
-- Generated by metaphor-schema

-- Create channel enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'channel') THEN
        CREATE TYPE channel AS ENUM ('whatsapp', 'email', 'sms');
    END IF;
END
$$;

-- Create thread_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'thread_status') THEN
        CREATE TYPE thread_status AS ENUM ('open', 'closed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS communication;

CREATE TABLE IF NOT EXISTS communication.threads (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    channel channel NOT NULL DEFAULT 'whatsapp',
    party_id UUID,
    subject_type TEXT,
    subject_id UUID,
    external_ref TEXT,
    status thread_status NOT NULL DEFAULT 'open',
    last_message_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_threads_company_id_party_id ON communication.threads (company_id, party_id);

CREATE INDEX IF NOT EXISTS idx_threads_subject_type_subject_id ON communication.threads (subject_type, subject_id);

CREATE INDEX IF NOT EXISTS idx_threads_status ON communication.threads (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_threads_metadata_gin ON communication.threads USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_threads_metadata_deleted_at ON communication.threads ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_threads_metadata_created_at ON communication.threads ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_threads_metadata_updated_at ON communication.threads ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION communication.threads_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS threads_insert_audit ON communication.threads;
CREATE TRIGGER threads_insert_audit BEFORE INSERT ON communication.threads
    FOR EACH ROW EXECUTE FUNCTION communication.threads_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS threads_update_audit ON communication.threads;
CREATE TRIGGER threads_update_audit BEFORE UPDATE ON communication.threads
    FOR EACH ROW EXECUTE FUNCTION communication.threads_audit_timestamp();
