//! Event handler trait for Message events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::MessageEvent;
use backbone_messaging::EventHandler;

/// Event handler for Message events.
/// Implement this trait to react to Message lifecycle events.
pub trait MessageEventHandler: EventHandler<MessageEvent> {}
