//! Event handler trait for Thread events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ThreadEvent;

/// Event handler for Thread events.
/// Implement this trait to react to Thread lifecycle events.
pub trait ThreadEventHandler: EventHandler<ThreadEvent> {}
