//! Domain events for Thread entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Thread;

/// Domain events for Thread — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Thread>)` variant.
pub type ThreadEvent = CrudEvent<Thread>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Thread events.
pub type ThreadEventPublisher = Arc<dyn CrudEventPublisher<Thread> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopThreadEventPublisher = NoOpCrudEventPublisher<Thread>;
