//! Event subscriber type aliases for Communication module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::MessageEvent;
use crate::domain::event::ThreadEvent;

/// Subscriber for Message events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type MessageEventSubscriber = GenericEventSubscriber<MessageEvent>;

/// Subscriber for Thread events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ThreadEventSubscriber = GenericEventSubscriber<ThreadEvent>;

// <<< CUSTOM
// END CUSTOM
