//! Repository trait for Message aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Message aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Message, Channel, Direction, MessageStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MessagePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl MessagePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct MessagePaginatedResult {
    pub data: Vec<Message>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct MessageFilter {
    pub thread_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub direction: Option<Direction>,
    pub channel: Option<Channel>,
    pub external_id: Option<String>,
    pub address_from: Option<String>,
    pub address_to: Option<String>,
    pub body: Option<String>,
    pub status: Option<MessageStatus>,
    pub failure_reason: Option<String>,
}

impl MessageFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.thread_id.is_some() || self.company_id.is_some() || self.direction.is_some() || self.channel.is_some() || self.external_id.is_some() || self.address_from.is_some() || self.address_to.is_some() || self.body.is_some() || self.status.is_some() || self.failure_reason.is_some()
    }
}

/// Repository trait for Message aggregate
///
/// This trait defines the persistence contract for Message entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait MessageRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new message entity
    async fn save(&self, entity: &Message) -> Result<Message>;

    /// Find message by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Message>>;

    /// Find all message entities
    async fn find_all(&self) -> Result<Vec<Message>>;

    /// Update message by ID
    async fn update(&self, id: &str, entity: &Message) -> Result<Option<Message>>;

    /// Delete message by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List message with pagination
    async fn list(&self, params: MessagePaginationParams) -> Result<MessagePaginatedResult>;

    /// List message with pagination and filters
    async fn list_with_filters(&self, params: MessagePaginationParams, filters: MessageFilter) -> Result<MessagePaginatedResult>;

    /// Count all message entities
    async fn count(&self) -> Result<u64>;

    /// Count message entities matching filters
    async fn count_with_filters(&self, filters: MessageFilter) -> Result<u64>;

    /// Check if message exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete message by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted message by ID
    async fn restore(&self, id: &str) -> Result<Option<Message>>;

    /// List soft-deleted message entities
    async fn list_deleted(&self, params: MessagePaginationParams) -> Result<MessagePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save message entities
    async fn bulk_save(&self, entities: &[Message]) -> Result<Vec<Message>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
