//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod message_repository;
pub mod thread_repository;

// Re-exports
pub use message_repository::{
    MessageRepository,
    MessagePaginationParams,
    MessagePaginatedResult,
    MessageFilter,
};
pub use thread_repository::{
    ThreadRepository,
    ThreadPaginationParams,
    ThreadPaginatedResult,
    ThreadFilter,
};
