//! Repository trait for Thread aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Thread aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Thread, Channel, ThreadStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ThreadPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ThreadPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ThreadPaginatedResult {
    pub data: Vec<Thread>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ThreadFilter {
    pub company_id: Option<Uuid>,
    pub channel: Option<Channel>,
    pub party_id: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub external_ref: Option<String>,
    pub status: Option<ThreadStatus>,
}

impl ThreadFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.channel.is_some() || self.party_id.is_some() || self.subject_type.is_some() || self.subject_id.is_some() || self.external_ref.is_some() || self.status.is_some()
    }
}

/// Repository trait for Thread aggregate
///
/// This trait defines the persistence contract for Thread entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ThreadRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new thread entity
    async fn save(&self, entity: &Thread) -> Result<Thread>;

    /// Find thread by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Thread>>;

    /// Find all thread entities
    async fn find_all(&self) -> Result<Vec<Thread>>;

    /// Update thread by ID
    async fn update(&self, id: &str, entity: &Thread) -> Result<Option<Thread>>;

    /// Delete thread by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List thread with pagination
    async fn list(&self, params: ThreadPaginationParams) -> Result<ThreadPaginatedResult>;

    /// List thread with pagination and filters
    async fn list_with_filters(&self, params: ThreadPaginationParams, filters: ThreadFilter) -> Result<ThreadPaginatedResult>;

    /// Count all thread entities
    async fn count(&self) -> Result<u64>;

    /// Count thread entities matching filters
    async fn count_with_filters(&self, filters: ThreadFilter) -> Result<u64>;

    /// Check if thread exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete thread by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted thread by ID
    async fn restore(&self, id: &str) -> Result<Option<Thread>>;

    /// List soft-deleted thread entities
    async fn list_deleted(&self, params: ThreadPaginationParams) -> Result<ThreadPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save thread entities
    async fn bulk_save(&self, entities: &[Thread]) -> Result<Vec<Thread>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
