//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod message_repository;
mod thread_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use message_repository::MessageRepository;
pub use thread_repository::ThreadRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written communication SQL's parameter/projection types (see `message_repository` and
// `thread_repository`, both declared `user_owned` in metaphor.codegen.yaml).
pub use message_repository::{MessageRefRow, NewInboundMessageRow, NewOutboundMessageRow};
pub use thread_repository::{NewRoutedThreadRow, NewThreadRow, RoutedThreadRow, ThreadSendRow};
// END CUSTOM