//! Repository for Thread entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Thread, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Thread;

/// Table name for Thread entities
pub const TABLE_NAME: &str = "communication.threads";

/// Repository for Thread entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ThreadRepository(
    backbone_orm::GenericCrudRepository<Thread, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ThreadRepository {
    type Target = backbone_orm::GenericCrudRepository<Thread, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ThreadRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ThreadRepository, Thread, soft_delete);
