//! Repository for Thread entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Thread SQL — the inbound routing lookups, the thread open/link/close
//! transitions (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Thread, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;

use crate::domain::entity::Thread;

/// Table name for Thread entities
pub const TABLE_NAME: &str = "communication.threads";

/// Repository for Thread entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ThreadRepository(backbone_orm::GenericCrudRepository<Thread, backbone_orm::SoftDelete>);

impl std::ops::Deref for ThreadRepository {
    type Target = backbone_orm::GenericCrudRepository<Thread, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ThreadRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// A routing lookup's projection: the thread and the subject it is CURRENTLY linked to (the persisted
/// `link_thread` value, which a follow-up webhook does not carry).
pub struct RoutedThreadRow {
    pub id: Uuid,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
}

/// The exact row an inbound-routed thread open writes — carries the webhook's subject hint.
pub struct NewRoutedThreadRow<'a> {
    pub id: Uuid,
    pub channel: &'a str,
    pub party_id: Option<Uuid>,
    pub external_ref: Option<&'a str>,
    pub subject_type: Option<&'a str>,
    pub subject_id: Option<Uuid>,
}

/// The exact row an explicit (outbound-initiated) thread open writes. No subject columns — an explicitly
/// opened thread is linked later via [`ThreadRepository::set_subject`], as the original write did.
pub struct NewThreadRow<'a> {
    pub id: Uuid,
    pub channel: &'a str,
    pub party_id: Option<Uuid>,
    pub external_ref: Option<&'a str>,
}

/// What an outbound send needs to know about its thread before it queues a message.
pub struct ThreadSendRow {
    pub channel: String,
    pub status: String,
}

fn to_routed(row: &sqlx::postgres::PgRow) -> RoutedThreadRow {
    RoutedThreadRow {
        id: row.get("id"),
        subject_type: row.get("subject_type"),
        subject_id: row.get("subject_id"),
    }
}

/// Hand-written Thread SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl ThreadRepository {
    /// Routing key #1: the most recent OPEN thread for a provider conversation handle.
    ///
    /// Takes the CALLER'S connection — it runs inside the inbound tx, onto which the caller has
    /// already relayed any ambient org scope; don't re-bind here.
    pub async fn find_open_by_external_ref(
        &self,
        conn: &mut sqlx::PgConnection,
        channel: &str,
        external_ref: &str,
    ) -> Result<Option<RoutedThreadRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT id, subject_type, subject_id FROM communication.threads
               WHERE channel=$1::channel AND external_ref=$2
                 AND status='open'::thread_status AND (metadata->>'deleted_at') IS NULL
               ORDER BY last_message_at DESC NULLS LAST LIMIT 1"#,
        )
        .bind(channel)
        .bind(external_ref)
        .fetch_optional(conn)
        .await?;
        Ok(row.as_ref().map(to_routed))
    }

    /// Routing key #2: the most recent OPEN thread for a party. Same caller-owned-tx contract as
    /// [`Self::find_open_by_external_ref`].
    pub async fn find_open_by_party(
        &self,
        conn: &mut sqlx::PgConnection,
        channel: &str,
        party_id: Uuid,
    ) -> Result<Option<RoutedThreadRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"SELECT id, subject_type, subject_id FROM communication.threads
               WHERE channel=$1::channel AND party_id=$2
                 AND status='open'::thread_status AND (metadata->>'deleted_at') IS NULL
               ORDER BY last_message_at DESC NULLS LAST LIMIT 1"#,
        )
        .bind(channel)
        .bind(party_id)
        .fetch_optional(conn)
        .await?;
        Ok(row.as_ref().map(to_routed))
    }

    /// Open a thread for an inbound message that routed to none. Same caller-owned-tx contract as the
    /// routing lookups — it must roll back with the message insert when the dedup claim loses its race.
    pub async fn open_routed_thread(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewRoutedThreadRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO communication.threads
                 (id, channel, party_id, external_ref, subject_type, subject_id, status)
               VALUES ($1,$2::channel,$3,$4,$5,$6,'open'::thread_status)"#,
        )
        .bind(t.id)
        .bind(t.channel)
        .bind(t.party_id)
        .bind(t.external_ref)
        .bind(t.subject_type)
        .bind(t.subject_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Open a thread explicitly (outbound-initiated conversation).
    ///
    /// Rides the request-dedicated connection when the composing service bound a scope — under a
    /// decorated deployment the fence's WITH CHECK governs the row; with no scope bound this is a
    /// plain insert.
    pub async fn insert_thread(
        &self,
        pool: &PgPool,
        t: &NewThreadRow<'_>,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO communication.threads (id, channel, party_id, external_ref, status)
                   VALUES ($1,$2::channel,$3,$4,'open'::thread_status)"#,
            )
            .bind(t.id)
            .bind(t.channel)
            .bind(t.party_id)
            .bind(t.external_ref),
        )
        .await?;
        Ok(())
    }

    /// Attach a thread to the business object it concerns. Returns the rows affected so the caller can
    /// turn a miss into a domain error.
    ///
    /// ID-only. Rides the request-dedicated connection when the composing service bound a scope —
    /// another unit's thread then simply isn't matched (fail closed) — and runs plainly when none
    /// is bound.
    pub async fn set_subject(
        &self,
        pool: &PgPool,
        thread_id: Uuid,
        subject_type: &str,
        subject_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE communication.threads SET subject_type=$2, subject_id=$3
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(thread_id)
            .bind(subject_type)
            .bind(subject_id),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Read the channel/status an outbound send needs. ID-only, same connection discipline as
    /// [`Self::set_subject`].
    pub async fn fetch_for_send(
        &self,
        pool: &PgPool,
        thread_id: Uuid,
    ) -> Result<Option<ThreadSendRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT channel::text AS channel, status::text AS status
                   FROM communication.threads WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(thread_id),
        )
        .await?;
        Ok(row.map(|r| ThreadSendRow {
            channel: r.get("channel"),
            status: r.get("status"),
        }))
    }

    /// Bump `last_message_at` inside the CALLER'S transaction, so it commits with the message insert.
    /// The caller has already relayed any ambient org scope onto it — don't re-bind here.
    pub async fn touch_last_message_on(
        &self,
        conn: &mut sqlx::PgConnection,
        thread_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE communication.threads SET last_message_at = now() WHERE id=$1")
            .bind(thread_id)
            .execute(conn)
            .await?;
        Ok(())
    }

    /// Bump `last_message_at` outside any transaction (the outbound-send path). Same connection
    /// discipline as [`Self::insert_thread`].
    pub async fn touch_last_message(
        &self,
        pool: &PgPool,
        thread_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE communication.threads SET last_message_at = now() WHERE id=$1")
                .bind(thread_id),
        )
        .await?;
        Ok(())
    }

    /// Close a thread. CAS-gated on `open`; returns the rows affected so the caller can turn a no-op into
    /// a domain error. ID-only, same connection discipline as [`Self::set_subject`].
    pub async fn mark_closed(&self, pool: &PgPool, thread_id: Uuid) -> Result<u64, sqlx::Error> {
        let done = org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE communication.threads SET status='closed'::thread_status
                   WHERE id=$1 AND status='open'::thread_status"#,
            )
            .bind(thread_id),
        )
        .await?;
        Ok(done.rows_affected())
    }
}

backbone_core::impl_crud_repository!(ThreadRepository, Thread, soft_delete);
