//! Validator for Thread entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Thread>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::Thread;

/// Validator type alias for Thread entities.
pub type ThreadValidator = EntityValidator<Thread>;

/// Build a validator for Thread with all schema-defined field rules.
pub fn thread_validator() -> ThreadValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("subject_type", |e: &Thread| e.subject_type.as_deref()))
        .rule(OptionalNotBlank::new("external_ref", |e: &Thread| e.external_ref.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
