//! Auth configuration for Message handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Message>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::MessageService;
use crate::domain::entity::Message;

/// Permission string constants for Message operations.
pub mod permissions {
    pub const LIST:        &str = "message:list";
    pub const READ:        &str = "message:read";
    pub const CREATE:      &str = "message:create";
    pub const UPDATE:      &str = "message:update";
    pub const DELETE:      &str = "message:delete";
    pub const RESTORE:     &str = "message:restore";
    pub const TRASH:       &str = "message:trash";
    pub const EMPTY_TRASH: &str = "message:empty_trash";
    pub const BULK_CREATE: &str = "message:bulk_create";
    pub const UPSERT:      &str = "message:upsert";
}

/// Resource policy for Message — maps CRUD actions to permission strings.
pub struct MessagePolicy;

#[async_trait]
impl ResourcePolicy<Message> for MessagePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Message,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Message handlers.
///
/// Wraps `MessageService` and checks `MessagePolicy` before delegating.
pub type MessageGuard = PermissionGuard<Message>;

/// Service-integrated permission guard for Message (for use in generated handlers).
pub type MessageServiceGuard = ServicePermissionGuard<Message, MessageService, MessagePolicy>;

// <<< CUSTOM
// END CUSTOM
