//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod message_auth;
pub mod thread_auth;

pub use message_auth::{MessagePolicy, MessageGuard, MessageServiceGuard};
pub use thread_auth::{ThreadPolicy, ThreadGuard, ThreadServiceGuard};

// <<< CUSTOM
// END CUSTOM
