//! Auth configuration for Thread handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Thread>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ThreadService;
use crate::domain::entity::Thread;

/// Permission string constants for Thread operations.
pub mod permissions {
    pub const LIST:        &str = "thread:list";
    pub const READ:        &str = "thread:read";
    pub const CREATE:      &str = "thread:create";
    pub const UPDATE:      &str = "thread:update";
    pub const DELETE:      &str = "thread:delete";
    pub const RESTORE:     &str = "thread:restore";
    pub const TRASH:       &str = "thread:trash";
    pub const EMPTY_TRASH: &str = "thread:empty_trash";
    pub const BULK_CREATE: &str = "thread:bulk_create";
    pub const UPSERT:      &str = "thread:upsert";
}

/// Resource policy for Thread — maps CRUD actions to permission strings.
pub struct ThreadPolicy;

#[async_trait]
impl ResourcePolicy<Thread> for ThreadPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Thread,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Thread handlers.
///
/// Wraps `ThreadService` and checks `ThreadPolicy` before delegating.
pub type ThreadGuard = PermissionGuard<Thread>;

/// Service-integrated permission guard for Thread (for use in generated handlers).
pub type ThreadServiceGuard = ServicePermissionGuard<Thread, ThreadService, ThreadPolicy>;

// <<< CUSTOM
// END CUSTOM
