//! Message API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Message CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// MESSAGE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Message
pub struct MessageTestData;

impl TestDataGenerator for MessageTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "thread_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "direction": "inbound",
            "channel": "whatsapp",
            "external_id": null,
            "address_from": null,
            "address_to": null,
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "received",
            "failure_reason": null,
            "occurred_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "thread_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "direction": "inbound",
            "channel": "whatsapp",
            "external_id": null,
            "address_from": null,
            "address_to": null,
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "received",
            "failure_reason": null,
            "occurred_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/threads", &super::thread_api_test::ThreadTestData).await {
            deps.push(("thread_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// MESSAGE API TEST
// ============================================================================

/// Message API test suite
pub struct MessageApiTest {
    inner: GenericCrudTest<MessageTestData>,
}

impl MessageApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/messages", "Message");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, MessageTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for MessageApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_message_crud() {
        let mut test = MessageApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Message specific tests here
// <<< CUSTOM TESTS END >>>
