//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod message_api_test;
pub mod thread_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use message_api_test::*;
pub use thread_api_test::*;
