//! Thread API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Thread CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// THREAD TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Thread
pub struct ThreadTestData;

impl TestDataGenerator for ThreadTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "channel": "whatsapp",
            "party_id": null,
            "subject_type": null,
            "subject_id": null,
            "external_ref": null,
            "status": "open",
            "last_message_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "channel": "whatsapp",
            "party_id": null,
            "subject_type": null,
            "subject_id": null,
            "external_ref": null,
            "status": "open",
            "last_message_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// THREAD API TEST
// ============================================================================

/// Thread API test suite
pub struct ThreadApiTest {
    inner: GenericCrudTest<ThreadTestData>,
}

impl ThreadApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/threads", "Thread");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ThreadTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ThreadApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_thread_crud() {
        let mut test = ThreadApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Thread specific tests here
// <<< CUSTOM TESTS END >>>
