//! Communication Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::MessageService;
use crate::application::service::ThreadService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Message service
    pub message_service: Arc<MessageService>,
    /// Thread service
    pub thread_service: Arc<ThreadService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        message_service: Arc<MessageService>,
        thread_service: Arc<ThreadService>
    ) -> Self {
        Self {
            message_service,
            thread_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::CommunicationModule) -> Self {
        Self {
            message_service: module.message_service.clone(),
            thread_service: module.thread_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    message_service: Option<Arc<MessageService>>,
    thread_service: Option<Arc<ThreadService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Message service.
    pub fn with_message_service(mut self, service: Arc<MessageService>) -> Self {
        self.message_service = Some(service);
        self
    }

    /// Set the Thread service.
    pub fn with_thread_service(mut self, service: Arc<ThreadService>) -> Self {
        self.thread_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            message_service: self.message_service.expect("message_service is required"),
            thread_service: self.thread_service.expect("thread_service is required"),
        }
    }
}
