//! Public events for Communication module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// MESSAGE EVENTS
// ============================================================================

/// Event published when a Message is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageCreatedEvent {
    pub id: MessageId,
    pub data: MessageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Message is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageUpdatedEvent {
    pub id: MessageId,
    pub data: MessageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Message is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageDeletedEvent {
    pub id: MessageId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// THREAD EVENTS
// ============================================================================

/// Event published when a Thread is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreadCreatedEvent {
    pub id: ThreadId,
    pub data: ThreadDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Thread is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreadUpdatedEvent {
    pub id: ThreadId,
    pub data: ThreadDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Thread is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreadDeletedEvent {
    pub id: ThreadId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Communication module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CommunicationEvent {
    MessageCreated(MessageCreatedEvent),
    MessageUpdated(MessageUpdatedEvent),
    MessageDeleted(MessageDeletedEvent),
    ThreadCreated(ThreadCreatedEvent),
    ThreadUpdated(ThreadUpdatedEvent),
    ThreadDeleted(ThreadDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommunicationEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for CommunicationEventMetadata {
    fn default() -> Self {
        Self {
            module: "communication",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
