//! Communication Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Communication exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use communication::exports::{MessageDto};
//! ```

mod events;
mod services;
mod types;

// Re-export all public types
pub use events::*;
pub use services::*;
pub use types::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `MessageDto` - Data transfer object for Message
/// - `MessageSummary` - Summary view of Message
/// - `MessageId` - Type-safe ID wrapper
/// - `ThreadDto` - Data transfer object for Thread
/// - `ThreadSummary` - Summary view of Thread
/// - `ThreadId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `MessageCreatedEvent` - Published when Message is created
/// - `MessageUpdatedEvent` - Published when Message is updated
/// - `MessageDeletedEvent` - Published when Message is deleted
/// - `ThreadCreatedEvent` - Published when Thread is created
/// - `ThreadUpdatedEvent` - Published when Thread is updated
/// - `ThreadDeletedEvent` - Published when Thread is deleted
pub struct ExportSummary;
