//! Public services for Communication module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Communication module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait CommunicationQueryService: Send + Sync {
    /// Get Message by ID
    async fn get_message(&self, id: MessageId) -> Result<Option<MessageDto>>;

    /// Get Message summary by ID
    async fn get_message_summary(&self, id: MessageId) -> Result<Option<MessageSummary>>;

    /// Check if Message exists
    async fn message_exists(&self, id: MessageId) -> Result<bool>;

    /// Get Thread by ID
    async fn get_thread(&self, id: ThreadId) -> Result<Option<ThreadDto>>;

    /// Get Thread summary by ID
    async fn get_thread_summary(&self, id: ThreadId) -> Result<Option<ThreadSummary>>;

    /// Check if Thread exists
    async fn thread_exists(&self, id: ThreadId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of CommunicationQueryService
pub struct CommunicationQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> CommunicationQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
