//! Public types for Communication module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// MESSAGE TYPES
// ============================================================================

/// Type-safe ID for Message
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MessageId(pub Uuid);

impl MessageId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for MessageId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<MessageId> for Uuid {
    fn from(id: MessageId) -> Self {
        id.0
    }
}

/// Data transfer object for Message
///
/// This is the public representation of Message for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageDto {
    pub id: MessageId,
    pub thread_id: Uuid,
    pub company_id: Uuid,
    pub direction: Direction,
    pub channel: Channel,
    pub external_id: Option<String>,
    pub address_from: Option<String>,
    pub address_to: Option<String>,
    pub body: String,
    pub status: MessageStatus,
    pub failure_reason: Option<String>,
    pub occurred_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of Message for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageSummary {
    pub id: MessageId,
    pub status: MessageStatus,
}

/// Reference to Message for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageRef {
    pub id: MessageId,
}

// ============================================================================
// THREAD TYPES
// ============================================================================

/// Type-safe ID for Thread
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ThreadId(pub Uuid);

impl ThreadId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ThreadId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ThreadId> for Uuid {
    fn from(id: ThreadId) -> Self {
        id.0
    }
}

/// Data transfer object for Thread
///
/// This is the public representation of Thread for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreadDto {
    pub id: ThreadId,
    pub company_id: Uuid,
    pub channel: Channel,
    pub party_id: Option<Uuid>,
    pub subject_type: Option<String>,
    pub subject_id: Option<Uuid>,
    pub external_ref: Option<String>,
    pub status: ThreadStatus,
    pub last_message_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Thread for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreadSummary {
    pub id: ThreadId,
    pub status: ThreadStatus,
}

/// Reference to Thread for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreadRef {
    pub id: ThreadId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
