//! Communication Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::MessageService;
pub use application::service::ThreadService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Communication module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let communication = CommunicationModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = communication.all_crud_routes();
/// ```
pub struct CommunicationModule {
    pub message_service: Arc<MessageService>,
    pub thread_service: Arc<ThreadService>,
}

impl CommunicationModule {
    /// Create a new module builder
    pub fn builder() -> CommunicationModuleBuilder {
        CommunicationModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_message_routes,
            create_thread_routes,
        };

        Router::new()
            .merge(create_message_routes(self.message_service.clone()))
            .merge(create_thread_routes(self.thread_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for CommunicationModule
pub struct CommunicationModuleBuilder {
    db_pool: Option<PgPool>,
}

impl CommunicationModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<CommunicationModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Message service
        let message_repository = Arc::new(MessageRepository::new(db_pool.clone()));
        let message_service = Arc::new(MessageService::with_repository(message_repository.clone()));

        // Thread service
        let thread_repository = Arc::new(ThreadRepository::new(db_pool.clone()));
        let thread_service = Arc::new(ThreadService::with_repository(thread_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(CommunicationModule {
            message_service,
            thread_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for CommunicationModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
