//! Use case type aliases for Message aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateMessageDto, UpdateMessageDto};
use crate::application::service::MessageService;
use crate::domain::entity::Message;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateMessageUseCase = CreateUseCase<Message, CreateMessageDto, MessageService>;
pub type UpdateMessageUseCase = UpdateUseCase<Message, UpdateMessageDto, MessageService>;
pub type GetMessageUseCase    = GetUseCase<Message, MessageService>;
pub type DeleteMessageUseCase = DeleteUseCase<Message, MessageService>;
pub type ListMessageUseCase   = ListUseCase<Message, MessageService>;

// <<< CUSTOM
// END CUSTOM
