//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod message_usecases;
pub mod thread_usecases;

pub use message_usecases::{
    CreateMessageUseCase, UpdateMessageUseCase, GetMessageUseCase,
    DeleteMessageUseCase, ListMessageUseCase,
};
pub use thread_usecases::{
    CreateThreadUseCase, UpdateThreadUseCase, GetThreadUseCase,
    DeleteThreadUseCase, ListThreadUseCase,
};

// <<< CUSTOM
// END CUSTOM
