//! Use case type aliases for Thread aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateThreadDto, UpdateThreadDto};
use crate::application::service::ThreadService;
use crate::domain::entity::Thread;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateThreadUseCase = CreateUseCase<Thread, CreateThreadDto, ThreadService>;
pub type UpdateThreadUseCase = UpdateUseCase<Thread, UpdateThreadDto, ThreadService>;
pub type GetThreadUseCase    = GetUseCase<Thread, ThreadService>;
pub type DeleteThreadUseCase = DeleteUseCase<Thread, ThreadService>;
pub type ListThreadUseCase   = ListUseCase<Thread, ThreadService>;

// <<< CUSTOM
// END CUSTOM
