//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod message_handler;
pub mod thread_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use message_handler::{create_message_routes, create_message_read_routes, create_message_write_routes};
pub use thread_handler::{create_thread_routes, create_thread_read_routes, create_thread_write_routes};
// <<< CUSTOM
// END CUSTOM
